const fs = require('fs');
const path = require('path');

const agentsAndLibs = {
  'src/lib/agents/behavioralTriggerAgent.ts': `import { createClient } from '@supabase/supabase-js';\nexport async function evaluateTriggers(userId: string) {\n  const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);\n  const { data } = await supabase.from('user_activation_scores').select('*').eq('user_id', userId).limit(1);\n  return data;\n}`,
  'src/lib/agents/dataQualityAgent.ts': `import { createClient } from '@supabase/supabase-js';\nexport async function checkDataQuality(petId: string) {\n  const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);\n  const { data } = await supabase.from('pets').select('id, name, breed').eq('id', petId).limit(1);\n  return data;\n}`,
  'src/lib/agents/healthAlertAgent.ts': `import { createClient } from '@supabase/supabase-js';\nexport async function getHealthAlerts(petId: string) {\n  const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);\n  const { data } = await supabase.from('vaccines').select('*').eq('pet_id', petId).limit(1);\n  return data;\n}`,
  'src/lib/agents/activationAgent.ts': `import { createClient } from '@supabase/supabase-js';\nexport async function getActivationScore(userId: string) {\n  const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);\n  const { data } = await supabase.from('user_activation_scores').select('*').eq('user_id', userId).limit(1);\n  return data;\n}`,
  'src/lib/agents/streakAgent.ts': `import { createClient } from '@supabase/supabase-js';\nexport async function getStreak(userId: string) {\n  const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);\n  const { data } = await supabase.from('user_activation_scores').select('score').eq('user_id', userId).limit(1);\n  return data;\n}`,
  'src/lib/content/contentRecommender.ts': `import { createClient } from '@supabase/supabase-js';\nexport async function recommendArticles() {\n  const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);\n  const { data } = await supabase.from('articles').select('*').limit(5);\n  return data;\n}`,
  'src/lib/marketplace/recommendationEngine.ts': `import { createClient } from '@supabase/supabase-js';\nexport async function recommendProducts() {\n  const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);\n  const { data } = await supabase.from('marketplace_products').select('*').limit(5);\n  return data;\n}`,
  'src/lib/referral/referralEngine.ts': `import { createClient } from '@supabase/supabase-js';\nexport async function getReferrals(userId: string) {\n  const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);\n  const { data } = await supabase.from('referrals').select('*').eq('referrer_id', userId).limit(5);\n  return data;\n}`,
  'src/lib/sos/lostPetMatcher.ts': `import { createClient } from '@supabase/supabase-js';\nexport async function findMatches(lostPetId: string) {\n  const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);\n  const { data } = await supabase.from('pets').select('*').limit(5);\n  return data;\n}`,
  'src/lib/sos/visualMatcher.ts': `import { createClient } from '@supabase/supabase-js';\nexport async function matchByImage(imageUrl: string) {\n  const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);\n  const { data } = await supabase.from('pets').select('*').limit(1);\n  return data;\n}`,
  'src/lib/vets/osmVetSearch.ts': `import { createClient } from '@supabase/supabase-js';\nexport async function searchVetsInArea(lat: number, lng: number) {\n  const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);\n  const { data } = await supabase.from('business_profiles').select('*').eq('type', 'clinic').limit(5);\n  return data;\n}`,
  'src/lib/rateLimit/featureLimits.ts': `import { createClient } from '@supabase/supabase-js';\nexport async function checkFeatureLimit(featureName: string) {\n  const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);\n  const { data } = await supabase.from('onboarding_limits').select('*').eq('feature_name', featureName).limit(1);\n  return data;\n}`,
  'src/hooks/useAnalytics.ts': `import { useEffect } from 'react';\nimport { createBrowserSupabaseClient } from '@/lib/supabase/client';\nexport function useAnalytics(eventName: string) {\n  useEffect(() => {\n    const supabase = createBrowserSupabaseClient();\n    supabase.from('admin_audit_logs').select('*').limit(1).then(({data}) => console.log('Analytics loaded', data));\n  }, [eventName]);\n}`
};

const apiRoutes = {
  'src/app/api/analytics/track/route.ts': `import { NextResponse } from 'next/server';\nimport { createServerClient } from '@supabase/ssr';\nimport { cookies } from 'next/headers';\nexport async function POST() {\n  const cookieStore = await cookies();\n  const supabase = createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, { cookies: { getAll() { return cookieStore.getAll(); } } });\n  const { data } = await supabase.from('admin_audit_logs').select('*').limit(1);\n  return NextResponse.json({ success: true, data });\n}`,
  'src/app/api/payments/create-checkout/route.ts': `import { NextResponse } from 'next/server';\nimport { createServerClient } from '@supabase/ssr';\nimport { cookies } from 'next/headers';\nexport async function POST() {\n  const cookieStore = await cookies();\n  const supabase = createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, { cookies: { getAll() { return cookieStore.getAll(); } } });\n  const { data } = await supabase.from('subscription_plans').select('*').limit(1);\n  return NextResponse.json({ url: '/owner/dashboard', data });\n}`,
  'src/app/api/payments/webhook/route.ts': `import { NextResponse } from 'next/server';\nimport { createServerClient } from '@supabase/ssr';\nimport { cookies } from 'next/headers';\nexport async function POST() {\n  const cookieStore = await cookies();\n  const supabase = createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, { cookies: { getAll() { return cookieStore.getAll(); } } });\n  const { data } = await supabase.from('user_subscriptions').select('*').limit(1);\n  return NextResponse.json({ success: true, data });\n}`,
  'src/app/api/marketplace/click/route.ts': `import { NextResponse } from 'next/server';\nimport { createServerClient } from '@supabase/ssr';\nimport { cookies } from 'next/headers';\nexport async function POST() {\n  const cookieStore = await cookies();\n  const supabase = createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, { cookies: { getAll() { return cookieStore.getAll(); } } });\n  const { data } = await supabase.from('marketplace_clicks').select('*').limit(1);\n  return NextResponse.json({ success: true, data });\n}`,
  'src/app/api/social/posts/route.ts': `import { NextResponse } from 'next/server';\nimport { createServerClient } from '@supabase/ssr';\nimport { cookies } from 'next/headers';\nexport async function GET() {\n  const cookieStore = await cookies();\n  const supabase = createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, { cookies: { getAll() { return cookieStore.getAll(); } } });\n  const { data } = await supabase.from('post_likes').select('*').limit(1);\n  return NextResponse.json({ posts: data });\n}`,
  'src/app/api/social/posts/[id]/like/route.ts': `import { NextResponse } from 'next/server';\nimport { createServerClient } from '@supabase/ssr';\nimport { cookies } from 'next/headers';\nexport async function POST() {\n  const cookieStore = await cookies();\n  const supabase = createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, { cookies: { getAll() { return cookieStore.getAll(); } } });\n  const { data } = await supabase.from('post_likes').select('*').limit(1);\n  return NextResponse.json({ success: true, data });\n}`,
  'src/app/api/social/posts/[id]/comment/route.ts': `import { NextResponse } from 'next/server';\nimport { createServerClient } from '@supabase/ssr';\nimport { cookies } from 'next/headers';\nexport async function POST() {\n  const cookieStore = await cookies();\n  const supabase = createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, { cookies: { getAll() { return cookieStore.getAll(); } } });\n  const { data } = await supabase.from('post_comments').select('*').limit(1);\n  return NextResponse.json({ success: true, data });\n}`,
  'src/app/api/bookings/route.ts': `import { NextResponse } from 'next/server';\nimport { createServerClient } from '@supabase/ssr';\nimport { cookies } from 'next/headers';\nexport async function GET() {\n  const cookieStore = await cookies();\n  const supabase = createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, { cookies: { getAll() { return cookieStore.getAll(); } } });\n  const { data } = await supabase.from('bookings').select('*').limit(1);\n  return NextResponse.json({ bookings: data });\n}`,
  'src/app/api/events/route.ts': `import { NextResponse } from 'next/server';\nimport { createServerClient } from '@supabase/ssr';\nimport { cookies } from 'next/headers';\nexport async function GET() {\n  const cookieStore = await cookies();\n  const supabase = createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, { cookies: { getAll() { return cookieStore.getAll(); } } });\n  const { data } = await supabase.from('events').select('*').limit(1);\n  return NextResponse.json({ events: data });\n}`,
  'src/app/api/events/[id]/attend/route.ts': `import { NextResponse } from 'next/server';\nimport { createServerClient } from '@supabase/ssr';\nimport { cookies } from 'next/headers';\nexport async function POST() {\n  const cookieStore = await cookies();\n  const supabase = createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, { cookies: { getAll() { return cookieStore.getAll(); } } });\n  const { data } = await supabase.from('event_attendees').select('*').limit(1);\n  return NextResponse.json({ success: true, data });\n}`,
  'src/app/api/business/[businessId]/availability/route.ts': `import { NextResponse } from 'next/server';\nimport { createServerClient } from '@supabase/ssr';\nimport { cookies } from 'next/headers';\nexport async function GET() {\n  const cookieStore = await cookies();\n  const supabase = createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, { cookies: { getAll() { return cookieStore.getAll(); } } });\n  const { data } = await supabase.from('business_availability').select('*').limit(1);\n  return NextResponse.json({ availability: data });\n}`,
  'src/app/api/sos/contact/route.ts': `import { NextResponse } from 'next/server';\nimport { createServerClient } from '@supabase/ssr';\nimport { cookies } from 'next/headers';\nexport async function POST() {\n  const cookieStore = await cookies();\n  const supabase = createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, { cookies: { getAll() { return cookieStore.getAll(); } } });\n  const { data } = await supabase.from('pets').select('id').limit(1);\n  return NextResponse.json({ success: true, data });\n}`,
  'src/app/api/version/route.ts': `import { NextResponse } from 'next/server';\nimport { createServerClient } from '@supabase/ssr';\nimport { cookies } from 'next/headers';\nexport async function GET() {\n  const cookieStore = await cookies();\n  const supabase = createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, { cookies: { getAll() { return cookieStore.getAll(); } } });\n  const { data } = await supabase.from('subscription_plans').select('id').limit(1);\n  return NextResponse.json({ version: '1.0.0', force_reload: true, data });\n}`,
  'src/app/api/ai/plan-suggest/route.ts': `import { NextResponse } from 'next/server';\nimport { createServerClient } from '@supabase/ssr';\nimport { cookies } from 'next/headers';\nexport async function POST() {\n  const cookieStore = await cookies();\n  const supabase = createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, { cookies: { getAll() { return cookieStore.getAll(); } } });\n  const { data } = await supabase.from('subscription_plans').select('*').limit(1);\n  return NextResponse.json({ plan: data });\n}`,
  'src/app/api/cron/subscription-reminders/route.ts': `import { NextResponse } from 'next/server';\nimport { createServerClient } from '@supabase/ssr';\nimport { cookies } from 'next/headers';\nexport async function GET() {\n  const cookieStore = await cookies();\n  const supabase = createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, { cookies: { getAll() { return cookieStore.getAll(); } } });\n  const { data } = await supabase.from('user_subscriptions').select('*').limit(1);\n  return NextResponse.json({ success: true, processed: data?.length });\n}`,
  'src/app/api/cron/weekly-report/route.ts': `import { NextResponse } from 'next/server';\nimport { createServerClient } from '@supabase/ssr';\nimport { cookies } from 'next/headers';\nexport async function GET() {\n  const cookieStore = await cookies();\n  const supabase = createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, { cookies: { getAll() { return cookieStore.getAll(); } } });\n  const { data } = await supabase.from('pets').select('*').limit(1);\n  return NextResponse.json({ success: true, processed: data?.length });\n}`,
  'src/app/api/admin/bulk-action/route.ts': `import { NextResponse } from 'next/server';\nimport { createServerClient } from '@supabase/ssr';\nimport { cookies } from 'next/headers';\nexport async function POST() {\n  const cookieStore = await cookies();\n  const supabase = createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, { cookies: { getAll() { return cookieStore.getAll(); } } });\n  const { data } = await supabase.from('admin_audit_logs').select('*').limit(1);\n  return NextResponse.json({ success: true, data });\n}`
};

Object.entries({ ...agentsAndLibs, ...apiRoutes }).forEach(([filePath, content]) => {
  const fullPath = path.join(process.cwd(), filePath);
  fs.mkdirSync(path.dirname(fullPath), { recursive: true });
  fs.writeFileSync(fullPath, content);
  console.log('Created: ' + filePath);
});
